source 'https://rubygems.org'

gem 'rake'
gem 'actionmailer', '3.2.11'
gem 'mongo'
gem 'bson_ext'
gem 'activesupport'

group :test do
	gem 'rspec', '2.12.0'
#	gem 'factory_girl', '4.2.0'
	gem 'simplecov'
	gem 'simplecov-rcov'
end
