// Generated by CoffeeScript 1.6.3
var Requestline;

Requestline = (function() {
  function Requestline(params) {
    this.params = params;
    this.validator = {
      "uid": /^[0-9]+$/,
      "timeslot": /^[0-2][0-9]-[0-2][0-9]$/
    };
  }

  Requestline.prototype.getParams = function() {
    return this.params;
  };

  Requestline.prototype.validate = function() {
    var key, value, _ref;
    _ref = this.params;
    for (key in _ref) {
      value = _ref[key];
      if (key in this.validator && this.validator[key].test(value) === false) {
        return false;
      }
    }
    return true;
  };

  return Requestline;

})();

exports.Requestline = Requestline;
