// Generated by CoffeeScript 1.6.3
var UserActionLogs, db, mongoose;
mongoose = require('mongoose');
var db = mongoose.createConnection('mongodb://localhost/action_log');

function validator(v) {
	return v.length > 0;
}

UserActionLogsSchema = new mongoose.Schema({
  user_id              : Number,
	event_id             : Number,
  event_genre_id       : Number,
  timeslot             : String,
  created_time         : String,
  update_time          : String
});

exports.UserActionLogs = db.model('user_action_logs', UserActionLogsSchema);
