// Generated by CoffeeScript 1.6.3
var UserEventSim, db, mongoose;
mongoose = require('mongoose');

var db = mongoose.createConnection('mongodb://localhost/recommend_data');

function validator(v) {
	return v.length > 0;
}

UserEventSimSchema = new mongoose.Schema({
  user_id       : Number,
	timeslot      : String,
	event_id      : Number,
  genre_id      : Number,
	title         : String,
  description   : String,
	imageurl      : String,
	similarity    : Number,
  created_time  : String,
  update_time   : String
});

exports.UserEventSim = db.model('user_event_similarities', UserEventSimSchema);
